### ISSUE TITLE
Does this library really support Semantic Patches?

### ISSUE THREAD

**Issue by rdohms** [launchdarkly/api-client-javascript#3]
API Docs say we need to set the Content-Type to have `domain-model=launchdarkly.semanticpatch` but looking over the code in this library I see no way to override the Content-Type since its hardcoded.

I'm trying to use the `patchFeatureFlag` method.

**Comment by carmenquan** [comment]
Hi @rdohms, thanks for your question. We do support semantic patch in this library, but not for all endpoints unfortunately. Our client library is auto-generated, and we can only support one type of response body per endpoint. Unfortunately `patchFeatureFlag` is annotated to accept JSON patch, you'll need to check each endpoint separately. 

In this example you can check the parameters here https://github.com/launchdarkly/api-client-javascript/blob/main/docs/FeatureFlagsApi.md#patchFeatureFlag, and if you click through you'll see this expects a JSON patch payload. 

I understand your feedback for having semantic patch for this endpoint and I hope we can get support for this in our client library when its available to our generator.

**Comment by ajmueller** [comment]
@carmenquan I came across this since I'm also hoping to use semantic patches with the `patchFeatureFlag` function. It appears that [the REST endpoint now supports semantic patch](https://apidocs.launchdarkly.com/tag/Feature-flags/#operation/patchFeatureFlag) (which I've confirmed with a direct REST API call), but it doesn't in the library. Does this mean the library needs to be re-generated?
